=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for OpsgenieSdk::CustomUserRoleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomUserRoleApi' do
  before do
    # run before each test
    @instance = OpsgenieSdk::CustomUserRoleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomUserRoleApi' do
    it 'should create an instance of CustomUserRoleApi' do
      expect(@instance).to be_instance_of(OpsgenieSdk::CustomUserRoleApi)
    end
  end

  # unit tests for create_custom_user_role
  # Create Custom User Role
  # Creates a new custom user role
  # @param body Request payload of created custom user role
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'create_custom_user_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_custom_user_role
  # Delete Custom User Role
  # Deletes a custom user role using role &#39;id&#39; or &#39;name&#39;
  # @param identifier Identifier of custom user role which could be user role &#39;id&#39; or &#39;name&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [SuccessResponse]
  describe 'delete_custom_user_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_custom_user_role
  # Get Custom User Role
  # Returns custom user role with given &#39;id&#39; or &#39;name&#39;
  # @param identifier Identifier of custom user role which could be user role &#39;id&#39; or &#39;name&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [GetCustomUserRoleResponse]
  describe 'get_custom_user_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_custom_user_roles
  # List Custom User Roles
  # Returns list of custom user roles
  # @param [Hash] opts the optional parameters
  # @return [ListCustomUserRolesResponse]
  describe 'list_custom_user_roles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_custom_user_role
  # Update Custom User Role
  # Updates the custom user role using role &#39;id&#39; or &#39;name&#39;
  # @param identifier Identifier of custom user role which could be user role &#39;id&#39; or &#39;name&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @option opts [UpdateCustomUserRolePayload] :body Request payload of update custom user role
  # @return [SuccessResponse]
  describe 'update_custom_user_role test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
