=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for OpsgenieSdk::EscalationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EscalationApi' do
  before do
    # run before each test
    @instance = OpsgenieSdk::EscalationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EscalationApi' do
    it 'should create an instance of EscalationApi' do
      expect(@instance).to be_instance_of(OpsgenieSdk::EscalationApi)
    end
  end

  # unit tests for create_escalation
  # Create Escalation
  # Creates a new escalation
  # @param body Request payload of created escalation
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'create_escalation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_escalation
  # Delete Escalation
  # Deletes an escalation using escalation &#39;id&#39; or &#39;name&#39;
  # @param identifier Identifier of escalation which could be escalation &#39;id&#39; or &#39;name&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [SuccessResponse]
  describe 'delete_escalation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_escalation
  # Get Escalation
  # Returns escalation with given &#39;id&#39; or &#39;name&#39;
  # @param identifier Identifier of escalation which could be escalation &#39;id&#39; or &#39;name&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [GetEscalationResponse]
  describe 'get_escalation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_escalations
  # List Escalations
  # Returns list of escalations
  # @param [Hash] opts the optional parameters
  # @return [ListEscalationsResponse]
  describe 'list_escalations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_escalation
  # Update Escalation (Partial)
  # Updates the escalation using escalation &#39;id&#39; or &#39;name&#39;
  # @param identifier Identifier of escalation which could be escalation &#39;id&#39; or &#39;name&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @option opts [UpdateEscalationPayload] :body Request payload of update escalation
  # @return [SuccessResponse]
  describe 'update_escalation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
