=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for OpsgenieSdk::ScheduleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScheduleApi' do
  before do
    # run before each test
    @instance = OpsgenieSdk::ScheduleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScheduleApi' do
    it 'should create an instance of ScheduleApi' do
      expect(@instance).to be_instance_of(OpsgenieSdk::ScheduleApi)
    end
  end

  # unit tests for create_schedule
  # Create Schedule
  # Creates a new schedule
  # @param body Request payload of created schedule
  # @param [Hash] opts the optional parameters
  # @return [CreateScheduleResponse]
  describe 'create_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_schedule
  # Delete Schedule
  # Delete schedule with given identifier
  # @param identifier Identifier of schedule which could be id or name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [SuccessResponse]
  describe 'delete_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for export_schedule
  # Export Schedule
  # Returns an .ics file as byte array
  # @param identifier Identifier of schedule which could be id or name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [String]
  describe 'export_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_schedule
  # Get Schedule
  # Returns schedule with given id or name
  # @param identifier Identifier of schedule which could be id or name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @return [GetScheduleResponse]
  describe 'get_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_schedule_timeline
  # Get Schedule Timeline
  # Returns schedule timeline with given id or name
  # @param identifier Identifier of schedule which could be id or name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @option opts [Array<String>] :expand Returns more detailed response with expanding it. Possible values are &#39;base&#39;, &#39;forwarding&#39;, and &#39;override&#39; which is also returned with expandable field of response
  # @option opts [Integer] :interval Length of time as integer in intervalUnits to retrieve the timeline. Default value is 1
  # @option opts [String] :interval_unit Unit of the time to retrieve the timeline. Available values are &#39;days&#39;, &#39;weeks&#39; and &#39;months&#39;. Default value is &#39;weeks&#39;
  # @option opts [DateTime] :date Time to return future date on-call participants. Default date is the moment of the time that request is received
  # @return [GetScheduleTimelineResponse]
  describe 'get_schedule_timeline test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_schedules
  # List Schedules
  # Returns list of schedule
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :expand Returns more detailed response with expanding it. Possible value is &#39;rotation&#39; which is also returned with expandable field of response
  # @return [ListSchedulesResponse]
  describe 'list_schedules test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_schedule
  # Update Schedule (Partial)
  # Update schedule with given id or name
  # @param identifier Identifier of schedule which could be id or name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :identifier_type Type of the identifier that is provided as an in-line parameter. Possible values are &#39;id&#39; or &#39;name&#39;
  # @option opts [UpdateSchedulePayload] :body Request payload of update schedule action
  # @return [UpdateScheduleResponse]
  describe 'update_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
