=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieSdk::AutoRestartAction
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AutoRestartAction' do
  before do
    # run before each test
    @instance = OpsgenieSdk::AutoRestartAction.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AutoRestartAction' do
    it 'should create an instance of AutoRestartAction' do
      expect(@instance).to be_instance_of(OpsgenieSdk::AutoRestartAction)
    end
  end
  describe 'test attribute "duration"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max_repeat_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
