=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieSdk::EscalationRule
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EscalationRule' do
  before do
    # run before each test
    @instance = OpsgenieSdk::EscalationRule.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EscalationRule' do
    it 'should create an instance of EscalationRule' do
      expect(@instance).to be_instance_of(OpsgenieSdk::EscalationRule)
    end
  end
  describe 'test attribute "condition"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["if-not-acked", "if-not-closed"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.condition = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "notify_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["default", "next", "previous", "users", "admins", "all"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.notify_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "delay"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "recipient"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
