=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieSdk::NotificationRepeat
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NotificationRepeat' do
  before do
    # run before each test
    @instance = OpsgenieSdk::NotificationRepeat.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationRepeat' do
    it 'should create an instance of NotificationRepeat' do
      expect(@instance).to be_instance_of(OpsgenieSdk::NotificationRepeat)
    end
  end
  describe 'test attribute "loop_after"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
