=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieSdk::UpdateAlertPriorityPayload
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdateAlertPriorityPayload' do
  before do
    # run before each test
    @instance = OpsgenieSdk::UpdateAlertPriorityPayload.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateAlertPriorityPayload' do
    it 'should create an instance of UpdateAlertPriorityPayload' do
      expect(@instance).to be_instance_of(OpsgenieSdk::UpdateAlertPriorityPayload)
    end
  end
  describe 'test attribute "priority"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["P1", "P2", "P3", "P4", "P5"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.priority = value }.not_to raise_error
      # end
    end
  end

end
