=begin
#Opsgenie REST API

#Opsgenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'date'

module OpsgenieSdk
  class NotifyTime
    
    JUST_BEFORE = 'just-before'.freeze
    N15_MINUTES_AGO = '15-minutes-ago'.freeze
    N1_HOUR_AGO = '1-hour-ago'.freeze
    N1_DAY_AGO = '1-day-ago'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = NotifyTime.constants.select { |c| NotifyTime::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #NotifyTime" if constantValues.empty?
      value
    end
  end
end
